apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: production
commonLabels:
  rendered-by: k8s-kustomize
  env: production

patches:
  - target:
      kind: Namespace
      name: echo-minikube
    patch: |-
      - op: replace
        path: /metadata/name
        value: production