apiVersion: v1
kind: Service
metadata:
  name: echo-minikube-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: echo-minikube-http
  selector:
    app: echo-minikube