apiVersion: v1
kind: Service
metadata:
  name: echo-minikube-service
  labels:
    app: echo-minikube
spec:
  ports:
    - protocol: TCP
      port: 7000
      targetPort: http
  selector:
    app: echo-minikube