apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
namespace: dev
commonLabels:
  rendered-by: k8s-kustomize
  env: dev
transformers:
  - namespace_transformer.yaml